### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by LianCadver** [depthbomb/Scraps#42] opened 2022-04-23 12:59 UTC
**Describe the bug**
Error in the title happens when I click the start button

**To Reproduce**
1. Insert cookie to the settings
2. Save
3. Click start button
4. Error happens

**Additional context**

```
19:58:15 Starting
19:58:15 "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Scraps.GUI.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 239
   at Scraps.GUI.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 112"
19:58:15 Stopped
```

**Comment by depthbomb** [comment] 2022-04-23 17:25
Duplicate of #41

**Closed as completed by depthbomb** 2022-04-23 17:25 UTC
Labels: bug
