### ISSUE TITLE
The end has come

### ISSUE THREAD

**Issue by bruhmomentobama** [depthbomb/Scraps#43] opened 2022-04-23 18:13 UTC
![image](https://user-images.githubusercontent.com/88178558/164934469-4e177a2d-4e2c-455e-9f57-9aa52f93b595.png)
This happens everytime you start it, I think they know we are using a different browser, so my suggestion to fix this is to have this use your main browser but without showing windows.

**Comment by depthbomb** [comment] 2022-04-23 18:35
Duplicate of #41

**Closed as completed by depthbomb** 2022-04-23 18:35 UTC
Labels: bug
